{
 "title": "Buildkite",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Running Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "buildkite_total_running_jobs_count"
    }
   ]
  },
  {
   "title": "Busy Agents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "buildkite_total_busy_agent_count"
    }
   ]
  },
  {
   "title": "Idle Agents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "buildkite_total_idle_agent_count"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Agent Busy % By Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "buildkite_queues_busy_agent_percentage",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Running Jobs By Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "buildkite_queues_running_jobs_count",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Idle Agents By Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "buildkite_queues_idle_agent_count",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Waiting Jobs By Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "buildkite_queues_waiting_jobs_count",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Scheduled Jobs By Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "buildkite_queues_scheduled_jobs_count",
     "legendFormat": "{{ queue }}"
    }
   ]
  }
 ]
}