apiVersion: v1
kind: Secret
metadata:
  name: {{ template "buildkite-agent-metrics.fullname" . }}-secret
  labels:
    app: {{ template "buildkite-agent-metrics.name" . }}
    chart: {{ template "buildkite-agent-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  BUILDKITE_AGENT_TOKEN: {{ .Values.buildkite.token | b64enc | quote }}
